export default {
    mode: 'jit',
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                current: "currentColor",
                transparent: "transparent",
                white: "#FFFFFF",
                body: "#64748B",
                primary: "#5925EB",
                graydark: "#333A48",
                whiten: "#F1F5F9",
                whiter: "#F5F7FD",
                grayColor: "#868599",
                grayColor2: "#82899B",
                "dm-blue": "#0E0D35",
                "vivid-purple": "#5825EB",
                teal: "#38E0B2",
                "ds-blue": "#575672",
                "soft-lilac": "#EDE8FD",
                "light-lilac": "#F2F4FB",
                "dl-gray": "#868599",
                "light-purple": "#7871F7",
                lavender: "#E7E7EB",
                "grayish-purple": "#6E6E86",
                "lavender-gray": "#CFCFD7",
                "rich-navy": "#051547",
                "lavender-gray-2": "#B7B7C3",
                "gray-blue-100": "#9F9EAE",
                "barely-peach": "#FFE9C7",
                "pale-pink-100": "#FFD7D7",
                "seafair-green": "#AEF7D3",
                "py-green": "#F1F7AE",
                "lavender-mist": "#",
                "gray-100": "#F1F6FF",
                "warning-50": "#DC8B13",
                "danger-50": "#FB1E1E",
                "green-200": "#D6FFEF",
                "white-500": "#FCFDFFB2",
                "white-100": "#FCFDFF",
                "blue-200": "#CCDDFF",
                "file-extension": "#00C650",
                "light-orange": "#ff5555",
                "dark-indigo-100": "#3E3D5D",
                "accent-green": "#00995C",
                "blush-100": "#FFE5E5",
                "chat-green": "#39F7AC",
                "profile-indicator": "#079E62",
                "info-warning": "#FCEED9",
                "peach-100": "#FCEED9",
                lightBlue: "#EBF3FA",
                failedColor: "#FF5555",
                "neutral-gray": "#D9D9D9",
                "silver-lining": "#EEF2F7",
                "bg-pdf-color": "#FF3E4C",
                "vibrant-Purple": "#A321EE",
                "light-blue": "#EAF1F8",
                "deep-indigo": "#27264A",
                "blue-gray": "#2B3F5A",
                "slate-700": "#5D6F7D",
                "electric-indigo": "#2B20E8",
                "blue-700": "#005FAD",
            },
        },
    },
    plugins: [],
};
