<template>
    <div class="d-flex justify-content-center align-items-center mt-5">
        <div class="register-form-box p-4 rounded-3 shadow">
            <div>
                <h5 class="fw-bold">Set Up Two-Factor Authentication</h5>
                <p class="mb-0">Download an Authenticator App</p>
                <div class="bg-body-secondary rounded-3 p-2 mb-3 text-center">
                    <p class="mb-0">Get the App - <b>Android Play</b> Store or <b>iOS App Store</b></p>
                </div>
                <div class="text-center">
                    <p class="mb-0">Scan QR code from the Authenticator App</p>
                    <img src="../../assets/image/qr_code.png" alt="qr code" class="img-fluid">
                </div>
                <p>Enter the 6-digit authentication code generated by the app:</p>
                <div class="d-flex justify-content-between">
                    <input type="text" maxlength="1" class="form-control text-center mx-1"
                        @input="moveToNext($event, 'input2')" id="input1">
                    <input type="text" maxlength="1" class="form-control text-center mx-1"
                        @input="moveToNext($event, 'input3')" id="input2">
                    <input type="text" maxlength="1" class="form-control text-center mx-1"
                        @input="moveToNext($event, 'input4')" id="input3">
                    <input type="text" maxlength="1" class="form-control text-center mx-1"
                        @input="moveToNext($event, 'input5')" id="input4">
                    <input type="text" maxlength="1" class="form-control text-center mx-1"
                        @input="moveToNext($event, 'input6')" id="input5">
                    <input type="text" maxlength="1" class="form-control text-center mx-1" id="input6">
                </div>
            </div>
            <button class="btn btn-primary w-100">Verify</button>
            <button class="btn btn-outline-primary w-100">Go to Dashboard</button>
        </div>
    </div>
</template>

<script setup>
const moveToNext = (event, nextInputId) => {
    const input = event.target;
    if (input.value.length === 1 && nextInputId) {
        document.getElementById(nextInputId).focus();
    }
};
</script>

<style scoped>
.register-form-box {
    background-color: #FCFDFFB2;
    max-width: 500px;
}

.btn {
    background-color: #6c63ff;
    color: #fff;
    width: 100%;
    padding: 12px;
    font-size: 16px;
    border-radius: 8px;
    border: none;
    cursor: pointer;
    margin-top: 20px;
}

.btn:hover {
    background-color: #5a54d1;
}

.form-control {
    border: none !important;
    border-radius: 8px !important;
    background-color: #F2F4FB;
}
</style>
