name: Deploy to Server

on:
  push:
    branches:
      - cockpit-deploy  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 3.29.86.231
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html2/doneeasysuperadmin
          git pull origin cockpit-deploy
          npm install
          npm run build
